### ISSUE TITLE
useless, cant even output. ("there's an error in xml document")

### ISSUE THREAD

**Issue by DemivalSecurity** [thomdixon/SaltwaterTaffy#8]
I only runs this extremely simple code. Expecting the result to be outputted into the console, it just directly give me that error. That also occurs in the demo project when I tried to compile into exe.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SaltwaterTaffy;
using SaltwaterTaffy.Container;

namespace testprogrssm
{
    class Program
    {
        static void Main(string[] args)
        {
            var target = new Target("192.168.0.0/24");
            var result = new Scanner(target).HostDiscovery();
            // do something with the result
            Console.WriteLine(result);
            Console.ReadLine();
        }
    }
}

```

Outputs this in Nmap.cs:
```
            return new ScanResult(ctx.Run()).Hosts;
System.InvalidOperationException: 'There is an error in XML document (0, 0).'
```

Demo Project output smh:
```
nhandled Exception: System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadernmaprun.Read61_nmaprun()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Simple.DotNMap.Extensions.Serialization.DeserializeFromFile[T](String filePath)
   at SaltwaterTaffy.NmapContext.Run() in C:\Users\user\Downloads\Compressed\SaltwaterTaffy-master\SaltwaterTaffy\Nmap.cs:line 634
   at SaltwaterTaffy.Scanner.PortScan() in C:\Users\user\Downloads\Compressed\SaltwaterTaffy-master\SaltwaterTaffy\Scanner.cs:line 322
   at SaltwaterTaffy.Demo.Program.Main(String[] args) in C:\Users\user\Downloads\Compressed\SaltwaterTaffy-master\SaltwaterTaffy.Demo\Program.cs:line 17
```

**Comment by thomdixon** [comment]
Sorry that you had issues running the demo!

The default scan used by `HostDiscovery()` (a TCP SYN scan with OS detection) requires root/administrative privileges in order to run. When running without sufficient privileges, this can result in the scan failing, which produces an empty XML document, and the result that you found. Please try running it again with root/administrative privileges.

I was able to get the demo running locally (with some minor changes for a Linux environment via Mono and `xbuild`), so I'm going to go ahead and close out this issue.
